//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

#![allow(dead_code)]

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// MFA daily metrics - aggregated by org and date. org_id = NULL for platform-wide rollups.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mfa_daily_metrics")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub org_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub date: String,
    pub total_users: i32,
    pub mfa_enabled_users: i32,
    pub new_mfa_setups: i32,
    pub mfa_disabled: i32,
    pub totp_verifications_total: i32,
    pub totp_verifications_success: i32,
    pub totp_verifications_failed: i32,
    pub backup_codes_generated: i32,
    pub backup_codes_used: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
