//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "oauth_states")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub state: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub pkce_verifier: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub service_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub redirect_uri: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub org_slug: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub service_slug: Option<String>,
    pub is_admin_flow: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_id_for_linking: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub device_user_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub saml_state_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub upstream_connection_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub requested_scopes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_state: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider_token_request_state: Option<String>,
    pub created_at: DateTime,
    pub expires_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserIdForLinking",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
