//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "organizations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub owner_user_id: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub tier_id: Option<String>,
    pub max_services: Option<i32>,
    pub max_users: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub approved_by: Option<String>,
    pub approved_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub rejected_by: Option<String>,
    pub rejected_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub rejection_reason: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing)]
    pub smtp_host: Option<String>,
    #[serde(skip_serializing)]
    pub smtp_port: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing)]
    pub smtp_username: Option<String>,
    #[sea_orm(column_type = "Blob", nullable)]
    #[serde(skip_serializing)]
    pub smtp_password_encrypted: Option<Vec<u8>>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing)]
    pub smtp_from_email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing)]
    pub smtp_from_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing)]
    pub smtp_encryption_key_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub custom_domain: Option<String>,
    pub domain_verified: bool,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing)]
    pub domain_verification_token: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub brand_logo_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub brand_primary_color: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub feature_overrides: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::memberships::Entity")]
    Memberships,
    #[sea_orm(has_many = "super::organization_audit_log::Entity")]
    OrganizationAuditLog,
    #[sea_orm(has_many = "super::organization_invitations::Entity")]
    OrganizationInvitations,
    #[sea_orm(has_many = "super::organization_oauth_credentials::Entity")]
    OrganizationOauthCredentials,
    #[sea_orm(
        belongs_to = "super::organization_tiers::Entity",
        from = "Column::TierId",
        to = "super::organization_tiers::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    OrganizationTiers,
    #[sea_orm(has_many = "super::services::Entity")]
    Services,
    #[sea_orm(has_many = "super::billing_customers::Entity")]
    BillingCustomers,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::RejectedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users3,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ApprovedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerUserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
    #[sea_orm(has_many = "super::webhooks::Entity")]
    Webhooks,
}

impl Related<super::memberships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Memberships.def()
    }
}

impl Related<super::organization_audit_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationAuditLog.def()
    }
}

impl Related<super::organization_invitations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationInvitations.def()
    }
}

impl Related<super::organization_oauth_credentials::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationOauthCredentials.def()
    }
}

impl Related<super::organization_tiers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationTiers.def()
    }
}

impl Related<super::services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Services.def()
    }
}

impl Related<super::billing_customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BillingCustomers.def()
    }
}

impl Related<super::webhooks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Webhooks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod serialization_tests {
    use super::*;

    #[test]
    fn generic_organization_json_omits_configuration_secrets() {
        let now = chrono::Utc::now().naive_utc();
        let organization = Model {
            id: "org-1".to_string(),
            slug: "acme".to_string(),
            name: "Acme".to_string(),
            owner_user_id: "user-1".to_string(),
            status: "active".to_string(),
            tier_id: None,
            max_services: None,
            max_users: None,
            approved_by: None,
            approved_at: None,
            rejected_by: None,
            rejected_at: None,
            rejection_reason: None,
            smtp_host: Some("smtp.example.com".to_string()),
            smtp_port: Some(587),
            smtp_username: Some("mailer".to_string()),
            smtp_password_encrypted: Some(vec![1, 2, 3]),
            smtp_from_email: Some("auth@example.com".to_string()),
            smtp_from_name: Some("Auth".to_string()),
            smtp_encryption_key_id: Some("key-1".to_string()),
            custom_domain: None,
            domain_verified: false,
            domain_verification_token: Some("verify-secret".to_string()),
            brand_logo_url: None,
            brand_primary_color: None,
            feature_overrides: None,
            created_at: now,
            updated_at: now,
        };
        let value = serde_json::to_value(organization).expect("organization should serialize");
        for field in [
            "smtp_host",
            "smtp_port",
            "smtp_username",
            "smtp_password_encrypted",
            "smtp_from_email",
            "smtp_from_name",
            "smtp_encryption_key_id",
            "domain_verification_token",
        ] {
            assert!(value.get(field).is_none(), "{field} must not be serialized");
        }
    }
}
