//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "organization_tiers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    pub default_max_services: i32,
    pub default_max_users: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub features: Option<String>,
    pub price_cents: i32,
    #[sea_orm(column_type = "Text")]
    pub currency: String,
    /// JSON mapping of billing provider to external price/product IDs
    /// e.g. {"stripe": "price_123", "polar": "prod_abc"}
    #[sea_orm(column_type = "Text", nullable)]
    pub external_mapping: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::organizations::Entity")]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
