//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "services")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub org_id: String,
    #[sea_orm(column_type = "Text")]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub service_type: String,
    #[sea_orm(column_type = "Text", unique)]
    pub client_id: String,
    #[sea_orm(column_type = "Text")]
    pub client_secret_hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub github_scopes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub microsoft_scopes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub google_scopes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub redirect_uris: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub device_activation_uri: Option<String>,
    pub saml_enabled: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub saml_entity_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub saml_acs_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub saml_slo_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub saml_name_id_format: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub saml_attribute_mapping: Option<String>,
    pub saml_sign_assertions: bool,
    pub saml_sign_response: bool,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_keys::Entity")]
    ApiKeys,
    #[sea_orm(has_many = "super::login_events::Entity")]
    LoginEvents,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(has_many = "super::plans::Entity")]
    Plans,
    #[sea_orm(has_many = "super::saml_signing_keys::Entity")]
    SamlSigningKeys,
    #[sea_orm(has_many = "super::saml_states::Entity")]
    SamlStates,
    #[sea_orm(has_many = "super::subscriptions::Entity")]
    Subscriptions,
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::login_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoginEvents.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::plans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plans.def()
    }
}

impl Related<super::saml_signing_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlSigningKeys.def()
    }
}

impl Related<super::saml_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlStates.def()
    }
}

impl Related<super::subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriptions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
