//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text", unique)]
    #[serde(skip_serializing)]
    pub token_hash: String,
    pub expires_at: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing)]
    pub refresh_token: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    #[serde(skip_serializing)]
    pub refresh_token_hash: Option<String>,
    pub refresh_token_expires_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub org_slug: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub service_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resource: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ip_address: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
