//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    /// Security Audit Item 1: Organization ID for multi-tenant isolation
    /// NULL = platform-level user (backward compatible)
    /// Some(id) = tenant-scoped user belonging to specific organization
    #[sea_orm(column_type = "Text", nullable)]
    pub org_id: Option<String>,
    pub is_platform_owner: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_hash: Option<String>,
    pub email_verified_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_keys::Entity")]
    ApiKeys,
    #[sea_orm(has_many = "super::device_codes::Entity")]
    DeviceCodes,
    #[sea_orm(has_many = "super::identities::Entity")]
    Identities,
    #[sea_orm(has_many = "super::login_events::Entity")]
    LoginEvents,
    #[sea_orm(has_many = "super::memberships::Entity")]
    Memberships,
    #[sea_orm(has_many = "super::mfa_audit_log::Entity")]
    MfaAuditLog,
    #[sea_orm(has_many = "super::mfa_failure_patterns::Entity")]
    MfaFailurePatterns,
    #[sea_orm(has_many = "super::mfa_feature_usage::Entity")]
    MfaFeatureUsage,
    #[sea_orm(has_many = "super::oauth_states::Entity")]
    OauthStates,
    #[sea_orm(has_many = "super::organization_audit_log::Entity")]
    OrganizationAuditLog,
    #[sea_orm(has_many = "super::organization_invitations::Entity")]
    OrganizationInvitations,
    #[sea_orm(has_many = "super::password_reset_tokens::Entity")]
    PasswordResetTokens,
    #[sea_orm(has_many = "super::platform_audit_log::Entity")]
    PlatformAuditLog,
    #[sea_orm(has_many = "super::saml_states::Entity")]
    SamlStates,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::subscriptions::Entity")]
    Subscriptions,
    #[sea_orm(has_many = "super::totp_backup_codes::Entity")]
    TotpBackupCodes,
    #[sea_orm(has_one = "super::user_totp_secrets::Entity")]
    UserTotpSecrets,
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::device_codes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceCodes.def()
    }
}

impl Related<super::identities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Identities.def()
    }
}

impl Related<super::login_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoginEvents.def()
    }
}

impl Related<super::memberships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Memberships.def()
    }
}

impl Related<super::mfa_audit_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MfaAuditLog.def()
    }
}

impl Related<super::mfa_failure_patterns::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MfaFailurePatterns.def()
    }
}

impl Related<super::mfa_feature_usage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MfaFeatureUsage.def()
    }
}

impl Related<super::oauth_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OauthStates.def()
    }
}

impl Related<super::organization_audit_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationAuditLog.def()
    }
}

impl Related<super::organization_invitations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationInvitations.def()
    }
}

impl Related<super::password_reset_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PasswordResetTokens.def()
    }
}

impl Related<super::platform_audit_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlatformAuditLog.def()
    }
}

impl Related<super::saml_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SamlStates.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriptions.def()
    }
}

impl Related<super::totp_backup_codes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TotpBackupCodes.def()
    }
}

impl Related<super::user_totp_secrets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTotpSecrets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
