//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "identities")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub provider: String,
    #[sea_orm(column_type = "Text")]
    pub provider_user_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing)]
    pub access_token: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing)]
    pub refresh_token: Option<String>,
    #[sea_orm(column_type = "Blob", nullable)]
    #[serde(skip_serializing)]
    pub access_token_encrypted: Option<Vec<u8>>,
    #[sea_orm(column_type = "Blob", nullable)]
    #[serde(skip_serializing)]
    pub refresh_token_encrypted: Option<Vec<u8>>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(skip_serializing)]
    pub encryption_key_id: Option<String>,
    pub expires_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub scopes: Option<String>,
    pub last_refreshed_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub issuing_org_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub issuing_service_id: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
