//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "saml_states")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub state_id: String,
    #[sea_orm(column_type = "Text")]
    pub service_id: String,
    #[sea_orm(column_type = "Text")]
    pub saml_request: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub relay_state: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub acs_url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub request_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub issuer: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub binding: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_id: Option<String>,
    pub created_at: DateTime,
    pub expires_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::services::Entity",
        from = "Column::ServiceId",
        to = "super::services::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Services,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Services.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
